FROM node:18.13 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN ng build --configuration production


FROM nginx:1.21.3-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx/production.conf /etc/nginx/conf.d/default.conf
