version: '3'
services:
  prodtrace-frontend:
    image: 45.32.22.181:5000/prodtrace_admin:latest
    #build: .
    ports:
      - "446:443"
    restart: always
    volumes:
      - /etc/letsencrypt/live/prodtrace.io/fullchain.pem:/etc/nginx/nginx-selfsigned.crt
      - /etc/letsencrypt/live/prodtrace.io/privkey.pem:/etc/nginx/nginx-selfsigned.key