FROM node:18.13 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --mode staging


FROM nginx:1.21.3-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx/staging.conf /etc/nginx/conf.d/default.conf
